### ISSUE TITLE
Musique de fond

### ISSUE THREAD

**Issue by Reda066** [Reda066/ProjetJavaScript#1]
Problème pour implémenter une musique de fond sur le navigateur google chrome.
Les codes testés marchent seulement sur internet explorer, par exemple : 

	  <audio controls autoplay loop hidden>
		<source src="musique.mp3" type="audio/mpeg">
		<p>If you can read this, your browser does not support the audio element.</p>
	</audio>

**Comment by micbuffa** [comment]
QU'est-ce qui ne marche pas ? A part le autoplay qui peut peut être violer les nouvelles recommandations? Vous avez ouvert la console d'erreur pour regarder ? 
Je vous conseille d'utiliser un "asset loader" pour les musiques et effets sonores : https://codepen.io/w3devcampus/pen/QpRGrz?editors=1010

**Comment by micbuffa** [comment]
Ceci n'est pas la correction de votre projet, mais un brouillon que j'ai écrit pour dégrossir les problèmes. https://jsbin.com/nohigiv/edit?js,console,output Il n'est pas fini mais peut vous montrer comment faire certaines choses... il y a encore bcp de choses à améliorer et de votre côté il faudra écrire un WebComponent (je suppose que Jordan vous en a parlé)...

**Comment by Reda066** [comment]
Problème résolue merci.
