### ISSUE TITLE
Les étoiles pour les scores

### ISSUE THREAD

**Issue by ZakariaG92** [Reda066/ProjetJavaScript#3]
J'ai réussie à dessiner les étoiles, mais j'ai pas réussi à les colorer depuis le DOM !

**Comment by ELHAROUI** [comment]
t'as utilisé quoi comme code pour dessiner et comment tu l'ai colore en HTLML ?

**Comment by ZakariaG92** [comment]
pour dessiner <span class="fa fa-star"></span>
pour colorer <span class="fa fa-star checked"></span>

**Comment by ELHAROUI** [comment]
alors dessine les simplement sans checked, et après l'incrémentation de score, appelle les et change ton attribut classe

**Comment by ZakariaG92** [comment]
Ok merci c'est fait !
